# I first need to import my R environment file for the 'neutral loci' dataset
load("/home/markoterzin/Documents/Parazoanthus_2bRAD/Marko/Script_validation_neutral_loci/O_and_Y/LEA/O_and_Y_neutral.RData")

# --------------------------- #
#
# Tutorial: 
# Admixture > Pie charts > Map
#
# Description:
# Tutorial on how to run STRUCTURE-like analyses in R, plot admixture proportions
# using pie charts, and visualise the pie charts on a map.
# 
# Data:
# European lobster SNP genotypes generated by a Fluidigm EP1 system.
# Tutorial uses ten sites from the original study (Jenkins et al. 2019).
# Data can be download from the link below:
# https://doi.org/10.5061/dryad.2v1kr38
# "lobster_1278ind_79snps_40pop.RData" in Miscellaneous_files.zip
#
# Notes before execution:
# 1. Make sure all required R packages are installed.
list.of.packages <- c("adegenet","poppr","LEA","reshape2","dplyr","ggplot2","reshape",
                      "rworldmap", "rworldxtra", "ggsn", "sf","ggsn","rgeos",
                      "raster", "rgeos", "maps","maptools", "grid", "miscTools", "stringr",
                      "ggpubr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

#####################################
# LEA package was a bit complicated #
#####################################
# if (!requireNamespace("BiocManager", quietly = TRUE))
# install.packages("BiocManager")
# BiocManager::install("LEA")

############
# and ggsn #
############
# I needed the dependencies units and sf
# units was installed by doing this first: https://zoomadmin.com/HowToInstall/UbuntuPackage/libudunits2-dev
# sf was installed this way: sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
# from https://r-spatial.github.io/sf/

# And then I installed ggsn from CRAN

# lastly, I needed to install package cowplot as dependency for ggpubr
# version 0.9.2 was available for R version 3.4
# install_version("cowplot", version = "0.9.2", repos = "http://cran.us.r-project.org")
# Now installing ggpubr

# 2. Set your working directory to the location of this R script.
setwd("/home/markoterzin/Documents/Parazoanthus_2bRAD/Marko/Script_validation_neutral_loci/O_and_Y/LEA/")

#
# --------------------------- #

# Load packages
library(adegenet)
library(poppr)
library(LEA)
library(reshape2) # This is only needed for the melt funtion
library(reshape)
library(dplyr)
library(ggplot2)
library(rworldmap)
library(rworldxtra)
library(ggsn)
library(sf)
library(raster)
library(rgeos)
library(maps)
library(maptools)
library(grid)
library(miscTools)
library(stringr)
library(ggpubr)

# Import genotypes
# read("lobster_1278ind_79snps_40pop.RData")

# Explore data
data_neutral_bayescan # This is the genind object I obtained already in the previous script
nLoc(data_neutral_bayescan) # number of loci
nPop(data_neutral_bayescan) # number of sites
nInd(data_neutral_bayescan) # number of individuals
summary(data_neutral_bayescan$pop) # sample size
# I have monomorphic loci, so remove these first
informative_data_final <- informloci(data_neutral_bayescan)


# Subset data to reduce computation time 
subsites_data = sort(c("ALA", "ALAOR", "CAMP", "CUB", "GIA", "PTF", "PUG", "PVEN", "PVENOR", "SAR", "GIAOR", "SAROR"))
# data_filt = popsub(data_final, sublist = subsites)
# data_filt


# ----------------- #
#
# Admixture analysis using SNMF from LEA
#
# ----------------- #

# Export genotypes in STRUCTURE format
source("TJ_genind2structure_function.R")
genind2structure(informative_data_final, file = "Parazoanthus_genotypes", pops = TRUE, markers = FALSE)

# Convert STRUCTURE file to .geno format
struct2geno("Parazoanthus_genotypes", ploidy = 2, FORMAT = 2, extra.column = 2)

# Run snmf algorithm

# My data
set.seed(123)
snmf1 = snmf("Parazoanthus_genotypes.geno",
             K = 1:15, # number of K ancestral populations to run
             repetitions = 10, # ten repetitions for each K
             entropy = TRUE, # calculate cross-entropy
             project = "new")

# Load snmf project
data_snmf1 = load.snmfProject("Parazoanthus_genotypes.snmfProject")
# Plot cross-entropy results to assess optimal number of K
# Smaller values of cross-entropy usually mean better runs
# A plateau usually represents the K that best fits the data

pdf("Cross_entropy_plot.pdf", 
    width = 15, height = 10)
# Plot
plot(data_snmf1, col = "blue", cex = 1.5, pch = 19)
# Close the pdf file
dev.off()

# Extract the cross-entropy of all runs where K = 2
data_ce = cross.entropy(data_snmf1, K = 2)
data_ce

# Find the run with the lowest cross-entropy
lowest.data_ce = which.min(data_ce)
lowest.data_ce

# Extract Q-matrix for the best run
qmatrix_data = as.data.frame(Q(data_snmf1, K = 2, run = lowest.data_ce))
head(qmatrix_data)

# Label column names of qmatrix
ncol(qmatrix_data)
data_cluster_names = c()
for (i in 1:ncol(qmatrix_data)){
  data_cluster_names[i] = paste("Cluster", i)
}
data_cluster_names
colnames(qmatrix_data) = data_cluster_names
head(qmatrix_data)

# Add individual IDs
qmatrix_data$Ind = indNames(informative_data_final)

# Add site IDs
qmatrix_data$Site = informative_data_final$pop
head(qmatrix_data)

# Convert dataframe to long format
qlong_data = melt(qmatrix_data, id.vars=c("Ind","Site"))
head(qlong_data)

# Change order of sites by using the factor function
site.order_data = c("ALA", "ALAOR", "CAMP", "CUB", "GIA", "PTF", "PUG", "PVEN", "PVENOR", "SAR", "GIAOR", "SAROR")
qlong_data$Site_ord = factor(qlong_data$Site, levels = site.order_data)

# Adjust facet labels my Parazoanthus
levels(qlong_data$Site)
facet.labs_data = c("ALA", "ALAOR", "CAMP", "CUB", "GIA", "PTF", "PUG", "PVEN", "PVENOR", "SAR", "GIAOR", "SAROR")
levels(qlong_data$Site) = facet.labs_data
levels(qlong_data$Site)

# Define colour palette
pal_data = colorRampPalette(c("khaki2", # Slender
                              "sandybrown")) # Stocky
cols_data = pal_data(length(unique(qlong_data$variable)))

# Plot admixture barplot
admix.bar_data = ggplot(data=qlong_data, aes(x=Ind, y=value, fill=variable))+
  geom_bar(stat = "identity")+
  scale_y_continuous(expand = c(0,0))+
  facet_wrap(~Site, scales = "free", ncol = 1)+
  facet_grid(~Site, scales = "free_x", space = "free")+
  scale_fill_manual(values = cols_data)+
  ylab("Admixture proportion")+
  xlab("Individual")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12),
        #axis.ticks.x = element_blank(),
        #axis.title.x = element_blank(),
        strip.text = element_text(colour="black", size=12),
        panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        legend.title = element_blank(),
        legend.text = element_text(size = 12))
admix.bar_data
ggsave("1.Parazoanthus_admixture_barplot.png", width=15, height=5, dpi=300)

# ----------------- #
#
# Prepare pie charts
#
# ----------------- #

# Calculate mean admixture proportions for each site
head(qmatrix_data)
clusters_data = grep("Cluster", names(qmatrix_data)) # indexes of cluster columns
avg_admix_data = aggregate(qmatrix_data[, clusters_data], list(qmatrix_data$Site), mean)

# Order alphabetically by site
avg_admix_data = avg_admix_data[order(as.character(avg_admix_data$Group.1)), ]
avg_admix_data

# Convert dataframe from wide to long format
avg_admix_data = melt(avg_admix_data, id.vars = "Group.1")
head(avg_admix_data)

# Define a function to plot pie charts using ggplot for each site
pie_charts = function(admix_df, site, cols){
  # admix_df = dataframe in long format of admixture proportions per site 
  # site = string 
  # cols = vector of colours of length(clusters)
  ggplot(data = subset(admix_df, Group.1 == site),
         aes(x = "", y = value, fill = variable))+
    geom_bar(width = 1, stat = "identity", colour = "black", show.legend = FALSE)+
    coord_polar(theta = "y")+
    scale_fill_manual(values = cols)+
    theme_void()
}

# Test function on one site
pie_charts(avg_admix_data, site = "ALA", cols = cols_data)

# Apply function to all sites using for loop: Parazoanthus
pies_data = list()
for (i in subsites_data){
  pies_data[[i]] = pie_charts(admix_df = avg_admix_data, site = i, cols = cols_data) 
}

# ----------------- #
#
# Prepare basemap
#
# ----------------- #

# Import csv file containing coordinates
coords_data = read.csv("coordinates_Par.csv")

# Subset coordinates (No need for my data, but let's see what happens)
coords_data = coords_data[coords_data$Code %in% subsites_data, ]

# Order alphabetically by site
coords_data = coords_data[order(coords_data$Code), ] 
coords_data

# Check order matches coords order
as.character(avg_admix_data$Group.1) == as.character(coords_data$Code)

# Set map boundary (xmin, xmax, ymin, ymax)
boundary_data = extent(0, 20, 35, 50)
boundary_data

# Get map outlines from rworldmap package
map.outline_data = getMap(resolution = "high")

# Crop to boundary and convert to dataframe
map.outline_data = crop(map.outline_data, y = boundary_data) %>% fortify()

# Plot basemap for Parazoanthus
basemap_data = ggplot()+
  geom_polygon(data=map.outline_data, aes(x=long, y=lat, group=group), fill="grey",
               colour="black", size=0.5)+
  coord_quickmap(expand=F)+
  ggsn::north(map.outline_data, symbol = 10, scale = 0.06, location = "topleft")+
  ggsn::scalebar(data = map.outline_data, dist = 200, dist_unit = "km", height = 0.01,
                 transform = TRUE, model = "WGS84", 
                 location = "bottomleft", # 200km distance is goinf bottom left 
                 anchor = c(x = 2.5, y = 35.5), # Where I want it anchored
                 st.bottom = FALSE, st.size = 4, st.dist = 0.015)+
  xlab("Longitude")+
  ylab("Latitude")+
  theme(
    axis.text = element_text(colour="black", size=12),
    axis.title = element_text(colour="black", size=14),
    panel.background = element_rect(fill="lightsteelblue2"),
    panel.border = element_rect(fill = NA, colour = "black", size = 0.5),
    panel.grid.minor = element_line(colour="grey90", size=0.5),
    panel.grid.major = element_line(colour="grey90", size=0.5),
    legend.text = element_text(size=12),
    legend.title = element_blank(),
    legend.key.size = unit(0.7, "cm"),
    legend.position = "top"
  )
basemap_data


# ----------------- #
#
# Add pie charts to basemap
#
# ----------------- #

# Extract coordinates for each site: Parazoanthus
coord.list_data = list()
for (i in subsites_data){
  coord.list_data[[i]] = c(subset(coords_data, Code == i)$Lon, subset(coords_data, Code == i)$Lat)
}
coord.list_data

# Define pie chart sizes
radius_data = 0.7

# Convert ggplot pie charts to annotation_custom layers: Parazoanthus
pies.ac_data = list()
for (i in 1:length(subsites_data)){
  pies.ac_data[[i]] = annotation_custom(grob = ggplotGrob(pies_data[[i]]),
                                   xmin = coord.list_data[[i]][[1]] - radius_data,
                                   xmax = coord.list_data[[i]][[1]] + radius_data,
                                   ymin = coord.list_data[[i]][[2]] - radius_data,
                                   ymax = coord.list_data[[i]][[2]] + radius_data)
}


# Add layers to basemap: Parazoanthus
pie.map_data = basemap_data + pies.ac_data
pie.map_data
ggsave("2.Parazoanthus.pie_charts_map.png", width = 8, height = 10, dpi = 300)

# Combine ggplots: Parazoanthus
data_combined <- ggarrange(pie.map_data + labs(title = "Mean admixture proportions for each site", tag = "B"),
admix.bar_data + theme(legend.position = "top") + labs(title = "Individual admixture proportions", tag = "A"))

ggsave("3.Admixture_bar_map.png", width = 15, height = 10, dpi = 300)

####################
# Now save as PDF! #
####################
pdf("3.Admixture_bar_map.pdf", 
    width = 15, height = 5)
# Plot
data_combined
# Close the pdf file
dev.off()

pdf("3.Par_map.pdf", 
    width = 15, height = 10)
# Plot
pie.map_data
# Close the pdf file
dev.off()

pdf("3.Admixture_Par.pdf", 
    width = 15, height = 5)
# Plot
admix.bar_data
# Close the pdf file
dev.off()
# And this was edited in Inkscape

# Now save this as RData file
save.image("O&Y_LEA_neutral_loci.RData")

###################
  ### THE END ###
###################
